name: Preview Changes

on:
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ['lint', 'types']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      - run: npm run ${{ matrix.command }}

  preview:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ['ShabadOS/next', 'ShabadOS/production']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ matrix.stack }}
          github-token: ${{ secrets.GH_BOT_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
