name: Release Changes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ['lint', 'types']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - run: npm run ${{ matrix.command }}

  deploy-environment:
    needs: checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ['next', 'production']
    environment:
      name: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ShabadOS/${{ matrix.environment }}
          work-dir: environment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          GITHUB_OWNER: shabados

  deploy-tools:
    needs: checks
    runs-on: ubuntu-latest
    environment:
      name: tools
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ShabadOS/tools
          work-dir: tools
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          GITHUB_OWNER: shabados
